### ISSUE TITLE
Handle grayscale images in backend

### ISSUE THREAD

**Issue by nitinsurya** [hpanwar08/document-layout-analysis-app#2]
The backend api currently throws a 500 error when a grayscale image is passed to `/analyse-image-json` endpoint, mentioning: `image.shape[2]` is out of index.

Updating the following code: https://github.com/hpanwar08/document-layout-analysis-app/blob/master/backend/project/api/dla_api.py#L22-L23 to

```
-    if image.shape[2] == 4:
+    if len(image.shape) == 2:  # grayscale image
+        image = cv2.cvtColor(image, cv2.COLOR_GRAY2BGR)
+    elif image.shape[2] == 4:
         image = cv2.cvtColor(image, cv2.COLOR_BGRA2BGR)
```

resolved the issue.

**Comment by hpanwar08** [comment]
Thanks for finding out this bug. Code was not written with grayscale in mind. I will correct this.
