### ISSUE TITLE
Little bug

### ISSUE THREAD

**Issue by under-score** [hpanwar08/document-layout-analysis-app#4]
on macOS Big Sur

![screen](https://user-images.githubusercontent.com/2796454/140634881-ea267f0f-4af4-4807-8fbd-1067810cb8c8.jpg)

**Comment by hpanwar08** [comment]
Did you retry it? All the dependencies are pinned it should not fail.

**Comment by under-score** [comment]
yes, also updated Docker, but no chance. Why not providing the container that I could pull directly?

**Comment by hpanwar08** [comment]
Change this line [libglib2.0-0=2.58.3-2+deb10u2](https://github.com/hpanwar08/document-layout-analysis-app/blob/master/backend/Dockerfile#L26)  to 
`libglib2.0-0`

**Comment by under-score** [comment]
thank you
